/**
 * Write per-platform slash command files. Source templates live in
 * `commands/*.md`; we substitute the skill root + version into a provenance
 * header, then write per platform.
 */
import { existsSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { FEATURE_COMMANDS, type FeatureId } from '../assets.js';
import { atomicWrite, ensureDir, toPosix } from '../fs-utils.js';
import { platformById, platformPaths, type Platform } from '../platforms.js';

const PROVENANCE_PREFIX = '# Generated by ui-forge@';

function templateBody(source: string, skillRoot: string, version: string): string {
  const header = `${PROVENANCE_PREFIX}${version} — do not edit, run \`ui-forge repair\` to regenerate.\n`;
  // Replace $CLAUDE_PLUGIN_ROOT with the resolved skill root (POSIX paths).
  const substituted = source.replace(/\$CLAUDE_PLUGIN_ROOT/g, toPosix(skillRoot));
  return header + substituted;
}

export interface WriteCommandsArgs {
  cwd: string;
  homedir: string;
  scope: 'project' | 'global';
  platformIds: string[];
  features: FeatureId[];
  sourceRoot: string;
  version: string;
  dryRun: boolean;
}

export interface WriteCommandsResult {
  written: string[];
  planned: string[];
}

export function writeCommands(args: WriteCommandsArgs): WriteCommandsResult {
  const { cwd, homedir, scope, platformIds, features, sourceRoot, version, dryRun } = args;
  const written: string[] = [];
  const planned: string[] = [];

  for (const id of platformIds) {
    const platform = platformById(id);
    if (!platform) continue;
    for (const scopeChoice of expandScope(scope)) {
      const paths = platformPaths(cwd, platform, scopeChoice, homedir);
      const skillRoot = paths.skillDir;
      ensureDir(paths.commandsDir);

      for (const feature of features) {
        const fileName = FEATURE_COMMANDS[feature];
        if (!fileName) continue;
        const sourcePath = join(sourceRoot, 'commands', fileName);
        if (!existsSync(sourcePath)) continue;
        const destPath = join(paths.commandsDir, fileName);
        const relForLock = toPosix(makeRel(cwd, destPath, scopeChoice));
        planned.push(relForLock);
        if (dryRun) continue;
        const body = templateBody(readFileSync(sourcePath, 'utf8'), skillRoot, version);
        atomicWrite(destPath, body);
        written.push(relForLock);
      }
    }
  }
  return { written, planned };
}

/**
 * Normalize scope to an array. Kept as a function for call-site symmetry;
 * 'both' is no longer a valid value (removed in 1.6.2).
 */
export function expandScope(scope: 'project' | 'global'): Array<'project' | 'global'> {
  return [scope];
}

/**
 * Stable lockfile-relative path: project paths are relative to cwd, global
 * paths are stored absolute.
 */
export function makeRel(cwd: string, abs: string, scope: 'project' | 'global'): string {
  if (scope === 'global') return abs;
  const rel = relative(cwd, abs);
  return rel || abs;
}

/**
 * Identify command files we own (have our provenance header) so the legacy
 * sweep / uninstall can act safely.
 */
export function isOwnedCommand(absPath: string): boolean {
  if (!existsSync(absPath)) return false;
  const head = readFileSync(absPath, 'utf8').slice(0, PROVENANCE_PREFIX.length + 64);
  return head.startsWith(PROVENANCE_PREFIX);
}
