/**
 * Bootstrap design/standards/ in the target project from the skill's
 * built-in standards sources (Issue 9 — theme standards bridging).
 *
 * Sources:
 *  - General standards: references/standards/*.md
 *  - Theme-specific standards: references/themes/<theme>/standards/*.md
 *    (configured per theme in STANDARDS_BY_THEME)
 *
 * Rules:
 *  - Files with a provenance header are safe to overwrite on re-install.
 *  - Files without the header are user-owned and never touched.
 *  - Always seeds the sample standard template as a starter.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import type { ThemeId } from '../assets.js';
import { STANDARDS_BY_THEME } from '../assets.js';
import { atomicWrite, ensureDir, isDirEmpty, pruneEmptyDirs, removeDir, removeFile, toPosix } from '../fs-utils.js';

const PROVENANCE_PREFIX = '<!-- Generated by ui-forge@';

function makeProvenance(version: string, sourceRel: string): string {
  return `${PROVENANCE_PREFIX}${version} from ${sourceRel} -->\n`;
}

function isProvenance(contents: string): boolean {
  return contents.trimStart().startsWith(PROVENANCE_PREFIX);
}

function copyWithProvenance(args: {
  srcAbs: string;
  destAbs: string;
  version: string;
  sourceRel: string;
  dryRun: boolean;
  copied: string[];
  cwd: string;
}): void {
  const { srcAbs, destAbs, version, sourceRel, dryRun, copied, cwd } = args;
  if (!existsSync(srcAbs)) return;

  if (existsSync(destAbs)) {
    const existing = readFileSync(destAbs, 'utf8');
    if (!isProvenance(existing)) return; // user-owned, skip
  }

  const srcContent = readFileSync(srcAbs, 'utf8');
  const header = makeProvenance(version, sourceRel);
  const output = header + srcContent;

  const rel = toPosix(
    destAbs.startsWith(cwd) ? destAbs.slice(cwd.length).replace(/^[\\/]/, '') : destAbs
  );
  copied.push(rel);

  if (!dryRun) {
    ensureDir(join(destAbs, '..'));
    atomicWrite(destAbs, output);
  }
}

export interface BootstrapArgs {
  cwd: string;
  sourceRoot: string;
  theme: ThemeId;
  version: string;
  dryRun: boolean;
}

export interface BootstrapResult {
  copied: string[];
}

export function bootstrapDesignStandards(args: BootstrapArgs): BootstrapResult {
  const { cwd, sourceRoot, theme, version, dryRun } = args;
  const copied: string[] = [];
  const destDir = join(cwd, 'design', 'standards');

  if (!dryRun) ensureDir(destDir);

  // Always: seed the sample standard template as _template-standard.md.
  // The underscore prefix matches scan.js's auto-registration filter so the
  // file is treated as a meta/template, not an active design standard.
  const sampleSrc = join(sourceRoot, 'references', 'standards', 'sample-standard.md');
  copyWithProvenance({
    srcAbs: sampleSrc,
    destAbs: join(destDir, '_template-standard.md'),
    version,
    sourceRel: 'references/standards/sample-standard.md',
    dryRun,
    copied,
    cwd,
  });

  // Always: seed nextjs-image.md (Issue 5). scan.js's copyBuiltinStandard
  // reads from CLAUDE_SKILL_DIR/references/standards/, which is no longer
  // copied into the skill dir — so the standard would otherwise never reach
  // the project. Seeded with provenance so theme/version bumps refresh it.
  copyWithProvenance({
    srcAbs: join(sourceRoot, 'references', 'standards', 'nextjs-image.md'),
    destAbs: join(destDir, 'nextjs-image.md'),
    version,
    sourceRel: 'references/standards/nextjs-image.md',
    dryRun,
    copied,
    cwd,
  });

  // Theme-specific standards
  const themeStandards = STANDARDS_BY_THEME[theme];
  if (themeStandards) {
    const { sourcePath, destSubdir } = themeStandards;
    const srcSubdir = join(sourceRoot, ...sourcePath.split('/'));
    if (existsSync(srcSubdir)) {
      const destAbs = join(destDir, destSubdir);
      if (!dryRun) ensureDir(destAbs);
      const files = readdirSync(srcSubdir).filter((f) => f.endsWith('.md'));
      for (const file of files) {
        copyWithProvenance({
          srcAbs: join(srcSubdir, file),
          destAbs: join(destAbs, file),
          version,
          sourceRel: `${sourcePath}/${file}`,
          dryRun,
          copied,
          cwd,
        });
      }
    }
  }

  return { copied };
}

/**
 * Remove theme-specific design standards subdirs whose theme is NOT the
 * current selection.
 *
 * Scans every known theme→subdir mapping in STANDARDS_BY_THEME and prunes
 * provenance-owned `.md` files in any subdir that doesn't match `nextTheme`.
 * Runs unconditionally on every install — does not depend on prior.theme,
 * so stale subdirs from before lockfile tracking was complete still get
 * cleaned up. User-customized files (no provenance header) are preserved.
 *
 * Returns the list of removed relative paths for lockfile tracking.
 */
export function pruneThemeStandards(args: {
  cwd: string;
  nextTheme: ThemeId;
  dryRun: boolean;
}): string[] {
  const { cwd, nextTheme, dryRun } = args;
  const keepSubdir = STANDARDS_BY_THEME[nextTheme];

  const standardsRoot = join(cwd, 'design', 'standards');
  if (!existsSync(standardsRoot)) return [];

  const removed: string[] = [];

  const keepDestSubdir = keepSubdir?.destSubdir;
  for (const [themeKey, cfg] of Object.entries(STANDARDS_BY_THEME)) {
    if (!cfg || cfg.destSubdir === keepDestSubdir) continue;
    const targetDir = join(standardsRoot, cfg.destSubdir);
    if (!existsSync(targetDir)) continue;

    let files: string[] = [];
    try {
      files = readdirSync(targetDir).filter((f) => f.endsWith('.md'));
    } catch { continue; }

    for (const file of files) {
      const abs = join(targetDir, file);
      let contents: string;
      try { contents = readFileSync(abs, 'utf8'); } catch { continue; }
      if (!isProvenance(contents)) continue; // user-customized, preserve
      const rel = toPosix(
        abs.startsWith(cwd) ? abs.slice(cwd.length).replace(/^[\\/]/, '') : abs
      );
      if (dryRun) {
        console.log(`  would prune design standard: ${rel} (theme '${themeKey}' not selected)`);
        continue;
      }
      try {
        removeFile(abs);
        removed.push(rel);
      } catch { /* non-fatal */ }
    }

    if (!dryRun) {
      // pruneEmptyDirs only removes empty *subdirs* of its arg — it never
      // removes the arg itself. Remove the theme subdir directly if all
      // provenance-owned files were deleted and nothing else remains.
      pruneEmptyDirs(targetDir);
      if (existsSync(targetDir) && isDirEmpty(targetDir)) removeDir(targetDir);
    }
  }

  return removed;
}
