/**
 * Generate the project-root `./ui-forge.mjs` shim. SKILL_ROOT is resolved at
 * runtime so the file is portable across machines (safe to commit).
 */
import { join } from 'node:path';
import { atomicWrite } from '../fs-utils.js';

const TEMPLATE = `#!/usr/bin/env node
// Auto-generated by \`ui-forge init\` (v__VERSION__). Do not edit — run \`ui-forge repair\` to regenerate.
// Resolves SKILL_ROOT at runtime so this file is portable across machines.
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';

function resolveSkillRoot() {
  if (process.env.UI_FORGE_SKILL_ROOT && existsSync(process.env.UI_FORGE_SKILL_ROOT)) {
    return process.env.UI_FORGE_SKILL_ROOT;
  }
  const localCandidates = [
    '.claude/skills/ui-forge',
    '.agents/skills/ui-forge',
    '.cursor/skills/ui-forge',
    '.codex/skills/ui-forge',
    '.copilot/skills/ui-forge',
    '.gemini/antigravity/skills/ui-forge',
  ];
  for (const rel of localCandidates) {
    const abs = resolve(process.cwd(), rel);
    if (existsSync(join(abs, 'scripts/invoke.js'))) return abs;
  }
  const globalCandidates = [
    join(homedir(), '.claude/skills/ui-forge'),
    join(homedir(), '.agents/skills/ui-forge'),
    join(homedir(), '.cursor/skills/ui-forge'),
  ];
  for (const abs of globalCandidates) {
    if (existsSync(join(abs, 'scripts/invoke.js'))) return abs;
  }
  console.error('UI Forge skill not found. Run \`pnpm dlx ui-forge init\` or set UI_FORGE_SKILL_ROOT.');
  process.exit(1);
}

const SCRIPTS = {
  scan: 'scripts/scan.js',
  forge: 'scripts/invoke.js',
  verify: 'scripts/verify.js',
  export: 'scripts/export-design.js',
  handoff: 'scripts/fetch-handoff.js',
  mcp: 'scripts/mcp-server.js',
};

const [, , cmd, ...rest] = process.argv;
const script = SCRIPTS[cmd];
if (!script) {
  console.error('Usage: node ui-forge.mjs <scan|forge|verify|export|handoff|mcp> [args]');
  process.exit(1);
}

const r = spawnSync(process.execPath, [join(resolveSkillRoot(), script), ...rest], { stdio: 'inherit' });
process.exit(r.status ?? 1);
`;

export interface ProjectCliArgs {
  cwd: string;
  version: string;
  dryRun: boolean;
}

export function writeProjectCli(args: ProjectCliArgs): string {
  const path = join(args.cwd, 'ui-forge.mjs');
  if (args.dryRun) return path;
  const body = TEMPLATE.replace(/__VERSION__/g, args.version);
  atomicWrite(path, body);
  return path;
}

export function projectCliPath(cwd: string): string {
  return join(cwd, 'ui-forge.mjs');
}
