/**
 * @contract-version 1.0.0
 *
 * StackShift Variant Router — HeroVariant props interface.
 * Generated by StackShift Step 3 (TypeScript types from Sanity schema).
 *
 * Rules (enforced by UI Forge SIGNAL_VARIANT + validate-contract.js):
 *   - Import this interface; do NOT redefine it.
 *   - Destructure every prop. Use `?? undefined` for optional props.
 *   - Return `null` when required props are absent.
 *   - Default export only — no additional named exports.
 */

export interface HeroVariantProps {
  headline: string
  subheadline?: string
  ctaLabel: string
  ctaHref: string
  backgroundImage?: {
    url: string
    alt: string
    width: number
    height: number
  }
  theme?: 'light' | 'dark'
}
